apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
spec:
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
        - name: c1
          image: mulawam/go-app:v2-mm
      imagePullSecrets:
        - name: docker-reg
