apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo-route
  namespace: default
spec:
  parentRefs:
  - name: podinfo-gateway
    namespace: default
    port: 443
    sectionName: https
  hostnames:
  - podinfo.public
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: podinfo-public-svc
      port: 8080
