apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: podinfo-gateway
  namespace: default
spec:
  gatewayClassName: tigera-gateway-class
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: podinfo.public
  - name: https
    port: 443
    protocol: HTTPS
    hostname: podinfo.public
    tls:
      mode: Terminate
      certificateRefs:
      - name: podinfo-public-tls
        kind: Secret